version: "3.8"

services:
  app:
    image: gitea/gitea:1-rootless
    restart: unless-stopped
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - app_data:/var/lib/gitea
      - app_config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      proxy_apps:
      default:
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - db_data:/var/lib/postgresql/data
    labels:
      ofelia.restart: "true"
      ofelia.enabled: "true"
      ofelia.job-exec.giteadbbackup.schedule: "0 0 1 * * *"
      ofelia.job-exec.giteadbbackup.command: "sh -c 'pg_dumpall -U gitea -f /var/lib/postgresql/data/backup.sql'"
    networks:
      default:


volumes:
  app_data:
  app_config:
  db_data:

networks:
  default:
  proxy_apps:
    name: proxy_apps
    external: true